server:
  port: 6002
eureka:
  instance:
    hostname: eureka2.com
  server:
    enable-self-preservation: false       #禁用保护,默认true;
    eviction-interval-timer-in-ms: 5000   #清理间隔（默认是60*1000）;
  client:
    service-url:
      defaultZone: http://eureka1.com:6001/eureka/    #单机,#集群互相指向;集群互相指向，除了自己之外的其它注册中心;
    register-with-eureka: true                     #单机false,默认true;
    fetch-registry: true                           #单机false,默认true;