server:
  port: 8001

spring:
  application:
    name: users-consumer

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:      # 也可以使用[lettuce]
      pool:
        max-idle: 50        # 最大空闲连接数
        min-idle: 10        # 最小空闲连接数
        max-wait:  -1s        # 等待可用连接的最大时间，负数为不限制
        max-active: -1        # 最大活跃连接数，负数为不限制

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
      #defaultZone: http://eureka1.com:6001/eureka/,http://eureka2.com:6002/eureka/


feign:
  hystrix:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

management:
  endpoints:
    web:
      exposure:
        #include: "*"
        include: hystrix.stream
  endpoint:
    health:
      show-details: ALWAYS

#负载均衡，默认轮询
#users-provider:
#  ribbon:
#    NFloadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule  #权重